// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XO_DEPI.Data;

#nullable disable

namespace XO_DEPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250226223249_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XO_DEPI.Core.Models.Battle", b =>
                {
                    b.Property<string>("FirstPlayer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SecondPlayer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FirstPlayerScore")
                        .HasColumnType("int");

                    b.Property<int>("SecondPlayerScore")
                        .HasColumnType("int");

                    b.HasKey("FirstPlayer", "SecondPlayer");

                    b.ToTable("battles");
                });
#pragma warning restore 612, 618
        }
    }
}
